-- TimeReport Supabase setup - fixed version
-- Paste this into Supabase Dashboard -> SQL Editor -> New query -> Run.
-- This creates the tables the React app expects, enables Row Level Security,
-- adds prototype policies, and creates starter login accounts.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  password_hash text not null,
  name text not null,
  role text not null check (role in ('employee', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  date date not null,
  company_id text not null,
  project_id text not null,
  hours numeric not null check (hours > 0 and hours <= 24),
  note text default '',
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.time_entries enable row level security;

-- Recreate policies so running this script more than once is safe.
drop policy if exists "prototype anon can read users" on public.users;
drop policy if exists "prototype anon can read time entries" on public.time_entries;
drop policy if exists "prototype anon can insert time entries" on public.time_entries;
drop policy if exists "prototype anon can delete time entries" on public.time_entries;

-- IMPORTANT: these policies are for getting the current prototype online.
-- They are permissive because this app currently does its own login in the browser.
-- For production, move login to Supabase Auth or a server-side function.
create policy "prototype anon can read users"
on public.users
for select
to anon
using (true);

create policy "prototype anon can read time entries"
on public.time_entries
for select
to anon
using (true);

create policy "prototype anon can insert time entries"
on public.time_entries
for insert
to anon
with check (true);

create policy "prototype anon can delete time entries"
on public.time_entries
for delete
to anon
using (true);

-- Remove only the prototype starter accounts if they already exist with wrong IDs.
-- Because time_entries.user_id has ON DELETE CASCADE, related prototype entries are removed too.
delete from public.users
where username in ('admin', 'anna', 'erik')
   or id in (
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000002',
    '00000000-0000-0000-0000-000000000003'
   );

-- Starter accounts for testing the app.
-- The current app compares the password in the browser, so these are plain text
-- despite the column being named password_hash.
insert into public.users (id, username, password_hash, name, role) values
  ('00000000-0000-0000-0000-000000000001', 'admin', 'admin123', 'Admin User', 'admin'),
  ('00000000-0000-0000-0000-000000000002', 'anna',  'anna123',  'Anna Employee', 'employee'),
  ('00000000-0000-0000-0000-000000000003', 'erik',  'erik123',  'Erik Employee', 'employee');

-- Optional sample entry so the admin dashboard is not empty.
insert into public.time_entries (user_id, date, company_id, project_id, hours, note)
values ('00000000-0000-0000-0000-000000000002', current_date, 'nordic_trials', 'nt_ops', 1.5, 'Sample entry');
